#!/bin/sh
### BEGIN INIT INFO
# Provides:          python-app
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Python application
### END INIT INFO

DAEMON=/opt/app/app.py
ARGS=/var/log/python-app.log
PIDFILE=/var/run/python-app.pid

case "$1" in
    start)
        echo "Starting python-app"
        start-stop-daemon -S -b -m -p $PIDFILE -x $DAEMON -- $ARGS
        ;;
    stop)
        echo "Stopping python-app"
        start-stop-daemon -K -p $PIDFILE
        ;;
    restart)
        $0 stop && $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
